import streamlit as st
import tensorflow as tf
import numpy as np

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from PIL import Image

# -------------------------
# Page Configuration
# -------------------------

st.set_page_config(
    page_title="AI Chest X-Ray Diagnosis",
    page_icon="🩻",
    layout="centered"
)

# -------------------------
# Load CNN Model
# -------------------------

@st.cache_resource
def load_cnn():
    model = load_model("pneumonia_cnn.keras")
    return model

model = load_cnn()

# -------------------------
# Title
# -------------------------

st.title("🩻 AI Chest X-Ray Diagnosis")

st.write(
    "Upload a Chest X-ray image and the AI model will predict whether the patient is Normal or has Pneumonia."
)

st.divider()

# -------------------------
# Upload Image
# -------------------------

uploaded_file = st.file_uploader(
    "Upload Chest X-ray",
    type=["jpg", "jpeg", "png"]
)

# -------------------------
# Prediction
# -------------------------

if uploaded_file is not None:

    image_display = Image.open(uploaded_file)

    st.image(
        image_display,
        caption="Uploaded Chest X-ray",
        use_container_width=True
    )

    img = image_display.resize((150,150))

    img_array = image.img_to_array(img)

    img_array = np.expand_dims(img_array, axis=0)

    img_array = img_array / 255.0

    prediction = model.predict(img_array, verbose=0)

    score = prediction[0][0]

    st.divider()

    st.subheader("Prediction")

    if score > 0.5:

        confidence = score * 100

        st.error("🫁 PNEUMONIA DETECTED")

        risk = "High"

    else:

        confidence = (1-score) * 100

        st.success("✅ NORMAL")

        risk = "Low"

    st.write(f"### Confidence : {confidence:.2f}%")

    st.write(f"### Risk Level : {risk}")

    st.write("---")

    st.info(
        "⚠️ This prediction is generated by an AI model and should not replace professional medical diagnosis."
    )
    