import streamlit as st
import numpy as np

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input
from PIL import Image

# ------------------------------------
# Page Configuration
# ------------------------------------

st.set_page_config(
    page_title="AI Chest X-Ray Diagnosis",
    page_icon="🩻",
    layout="centered"
)

# ------------------------------------
# Load ResNet50 Model
# ------------------------------------

@st.cache_resource
def load_resnet():
    return load_model("pneumonia_resnet50.keras")

model = load_resnet()

# ------------------------------------
# Title
# ------------------------------------

st.title("🩻 AI Chest X-Ray Diagnosis")

st.write(
    "Upload a Chest X-ray image and the AI model will predict whether the patient is Normal or has Pneumonia."
)

st.divider()

# ------------------------------------
# Upload Image
# ------------------------------------

uploaded_file = st.file_uploader(
    "Upload Chest X-ray",
    type=["jpg", "jpeg", "png"]
)

# ------------------------------------
# Prediction
# ------------------------------------

if uploaded_file is not None:

    image_display = Image.open(uploaded_file).convert("RGB")

    st.image(
        image_display,
        caption="Uploaded Chest X-ray",
        use_container_width=True
    )

    # Resize to 224x224 for ResNet50
    img = image_display.resize((224, 224))

    img_array = image.img_to_array(img)

    img_array = np.expand_dims(img_array, axis=0)

    # ResNet50 preprocessing
    img_array = preprocess_input(img_array)

    prediction = model.predict(img_array, verbose=0)

    score = prediction[0][0]

    st.divider()

    st.subheader("Prediction")

    if score > 0.5:

        confidence = score * 100

        diagnosis = "🫁 PNEUMONIA"

        risk = "HIGH"

        recommendation = (
            "Signs of pneumonia detected. Please consult a healthcare professional."
        )

        st.error(diagnosis)

    else:

        confidence = (1 - score) * 100

        diagnosis = "✅ NORMAL"

        risk = "LOW"

        recommendation = (
            "No obvious signs of pneumonia detected."
        )

        st.success(diagnosis)

    st.metric("Confidence", f"{confidence:.2f}%")

    st.metric("Risk Level", risk)

    st.info(recommendation)

    st.warning(
        "⚠️ This prediction is generated by an AI model and should not replace professional medical diagnosis."
    )